title: 나르의 블로그
author: Yujeong Jang
email: code.gnar@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  백엔드 개발자 유정의 블로그입니다. 개발 경험과 기술적 인사이트를 공유합니다.
show_excerpts: true

collections:
  memoirs:
    output: true
sass:
  sass_dir: _sass
plainwhite:
  name: 나르의 블로그
  tagline: Backend Developer
  intro: |
    코드로 문제를 해결하고,
    
    더 나은 솔루션을 찾아갑니다
  date_format: "%b %-d, %Y"
  sitemap: true
  search: true
  # analytics_id: G-HCKCGPDD5F
  dark_mode: never
  portfolio_image: "assets/images/portfolio.jpeg"
  html_lang: "KR"
  condensed_mobile:
    - page
    - post
    - category_archive
  # generate social links in footer
  social_links:
    github: im-gnar
    linkedIn: in/im-gnar
    #instagram: jekyll
    email: code.gnar@gmail.com
  navigation:
    - title: Resume
      url: "/resume"
    - title: Posts
      url: "/"
    - title: Categories
      url: "/categories"
    - title: Memoirs
      url: "/memoirs"

# --------------------------------------  Resume Config  --------------------------------------

# Site
repository: im-gnar/im-gnar.github.io

# Content configuration version
version: 2

# Personal info
resume_name: 장유정
resume_title: Backend Developer
resume_email: code.gnar@gmail.com
website: https://im-gnar.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
linkedin_username: im-gnar
github_username: im-gnar
#facebook_username: jekyll
#twitter_username: jekyllrb
#googlescholar_username: D847cGsAAAAJ

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "G-HCKCGPDD5F"
# google_analytics: "UA-00000000-0"

# About Section
about_profile_image: assets/images/gnar.jpeg
about_content: |
  > **생산성을 높여, 더 큰 가치를 만듭니다.**

  단순한 자동화를 넘어, 팀이 핵심 업무에 집중할 수 있는 환경을 만들기 위해 노력합니다. 반복적이고 비효율적인 업무를 발견하고, 문제 원인을 분석해 시스템화합니다. 이를 통해 팀의 업무 시간을 절감하고, 조직 전체의 업무 흐름을 개선해왔습니다.
  <br/><br/>
  > **꾸준히 배우며 더 나은 해결책을 찾습니다.**
  
  프로그래밍은 정답이 없고 트레이드오프의 연속이라고 생각합니다. 다양한 스킬셋의 장단점을 깊이 이해하며, 상황에 맞는 최적의 해결책을 찾는 데 집중합니다. 이러한 노력은 더 나은 아키텍처 설계와 합리적인 기술 선택으로 이어진다고 믿습니다.
  <br/><br/>
  > **지식을 나누며 함께 성장합니다.**
  
  배운 지식을 나누는 것은 단순한 공유를 넘어, 팀과 조직의 발전에 기여하는 길이라고 생각합니다. 사내 스터디와 발표를 통해 새로운 기술과 인사이트를 함께 탐구해왔습니다.

# -------------------------------------- END Resume Config  --------------------------------------

# Build settings
remote_theme: samarsault/plainwhite-jekyll
# theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
